/*
 * generated by Xtext 2.22.0
 */
package conway.rules;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RulesDSLStandaloneSetup extends RulesDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new RulesDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
