/*
 * generated by Xtext 2.22.0
 */
package ev3.behaviours.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ev3.behaviours.DSLRuntimeModule;
import ev3.behaviours.DSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DSLIdeSetup extends DSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DSLRuntimeModule(), new DSLIdeModule()));
	}
	
}
