/*
 * generated by Xtext 2.22.0
 */
package persons.tasks.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import persons.tasks.TaskDSLRuntimeModule;
import persons.tasks.TaskDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TaskDSLIdeSetup extends TaskDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TaskDSLRuntimeModule(), new TaskDSLIdeModule()));
	}
	
}
