/*
 * generated by Xtext 2.22.0
 */
package conway.rules.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import conway.rules.RulesDSLRuntimeModule;
import conway.rules.RulesDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RulesDSLIdeSetup extends RulesDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RulesDSLRuntimeModule(), new RulesDSLIdeModule()));
	}
	
}
