/*
 * generated by Xtext 2.22.0
 */
package persons.tasks;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TaskDSLRuntimeModule extends AbstractTaskDSLRuntimeModule {
}
