/*
 * generated by Xtext 2.22.0
 */
package persons.tasks;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TaskDSLStandaloneSetup extends TaskDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new TaskDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
