/*
 * generated by Xtext 2.22.0
 */
package ev3.behaviours;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
