/*
 * generated by Xtext 2.22.0
 */
package persons.tasks.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TaskDSLUiModule extends AbstractTaskDSLUiModule {

	public TaskDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
