/*
 * generated by Xtext 2.22.0
 */
package ev3.behaviours.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class DSLProposalProvider extends AbstractDSLProposalProvider {
}
