/*
 * generated by Xtext 2.22.0
 */
package conway.rules.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RulesDSLUiModule extends AbstractRulesDSLUiModule {

	public RulesDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
